name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        emacs_version:
          - 29.2
          - 29.4
    env:
      EMACS_VERSION: ${{ matrix.emacs_version }}
    steps:
      - uses: actions/setup-node@v4
      - run: npm i -g esy
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: actions/checkout@v2

      - name: Test
        run: |
          make test
